import { readTicks, setTick } from "../lib/db.js";
import { BY_ID } from "../lib/items.js";

// Period keys are generated by the page, so validate the shape rather than
// trusting it: 2026-09, 2026-Q3, 2026-H2, 2026, acsph2025, once, cycle, setup.
const KEY_OK = /^(\d{4}(-(\d{2}|Q[1-4]|H[1-2]))?|a[a-z0-9]{1,20}\d{4}|once|cycle|setup)$/;

// The setup checklist lives outside the item list.
const SETUP_IDS = new Set([
  "s_ent", "s_wmt", "s_resy", "s_lulu", "s_uber", "s_air", "s_dash", "s_eqx",
]);

export default async function handler(req, res) {
  try {
    if (req.method === "GET") {
      const raw = (req.query.periods || "").split(",").map((s) => s.trim()).filter(Boolean);
      const keys = raw.filter((k) => KEY_OK.test(k));
      if (!keys.length) return res.status(400).json({ error: "No valid period keys given." });
      res.setHeader("Cache-Control", "no-store");
      return res.status(200).json(await readTicks(keys));
    }

    if (req.method === "POST") {
      const { periodKey, itemId, ticked } = req.body ?? {};

      if (typeof periodKey !== "string" || !KEY_OK.test(periodKey)) {
        return res.status(400).json({ error: `Unrecognised period key: ${periodKey}` });
      }
      if (typeof itemId !== "string" || (!BY_ID[itemId] && !SETUP_IDS.has(itemId))) {
        return res.status(400).json({ error: `Unknown item: ${itemId}` });
      }
      if (typeof ticked !== "boolean") {
        return res.status(400).json({ error: "`ticked` must be true or false." });
      }

      await setTick(periodKey, itemId, ticked);
      return res.status(200).json({ ok: true });
    }

    res.setHeader("Allow", "GET, POST");
    return res.status(405).json({ error: "Method not allowed." });
  } catch (err) {
    // Never leak the connection string or driver internals to the browser.
    console.error("ticks:", err);
    return res.status(500).json({ error: "Could not reach the database." });
  }
}
